name: gh-monitor

on:
  workflow_call:
    inputs:
      fail:
        default: false
      
    secrets:
      GH_TOKEN:
        description: Github token        required: true


permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  issue-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: monitor issues
        run: |
          if [ "$(gh search issues --repo $GITHUB_REPOSITORY)" && $(fail) ]; then
            exit(1)
          fi
          echo "opened issues in $GITHUB_REPOSITORY"
          gh search issues --repo $GITHUB_REPOSITORY --state open
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  prs-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: monitor prs
        run: |
          echo "opened prs in $GITHUB_REPOSITORY"
          gh search prs --repo $GITHUB_REPOSITORY --state open
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
